<?php 
    function obter_dados(){
        $dados=[
            [
                "nome"=>"Thiago",
                "idade"=>30,
                "estado"=>"MG"
            ],
            [
                "nome"=>"Thaís",
                "idade"=>15,
                "estado"=>"SP"
            ],
            [
                "nome"=>"Roberto",
                "idade"=>10,
                "estado"=>"RJ"
            ],
            [
                "nome"=>"Vanessa",
                "idade"=>22,
                "estado"=>"SP"
            ],
            [
                "nome"=>"Junior",
                "idade"=>40,
                "estado"=>"BA"
            ],
        ];
        return $dados;
    }
?>